### ISSUE TITLE
How to add the Current DATE before the copied TITLE and URL?

### ISSUE THREAD

**Issue by sfd99** [k08045kk/CopyTabTitleUrl#27]
Easy, very useful Chrome addon.
Thank you!

**Q:**
how do I add the _Current DATE_
before the copied TITLE and URL.

I tried 
in the "format" options field:

    ${yyyy}-${MM}-${dd})-[${title}](${url})

(but my format syntax must be wrong...).

_**Help!**_
sfd99
San Francisco
latest Chrome browser
Ubuntu LINUX 20.04

**Comment by k08045kk** [comment]
Duplicate #28
