### ISSUE TITLE
Feature Request: Keyboard Shortcut

### ISSUE THREAD

**Issue by damengilland** [k08045kk/CopyTabTitleUrl#3]
I used to use this, but it is no longer supported.

* Make Link – Add-ons for Firefox || https://addons.mozilla.org/en-US/firefox/addon/make-link/

In Chrome I was using this, and I generally thought it was perfect because I could customize the way the link was copied, and set a keyboard shortcut:

* Create Link - Chrome Web Store || https://chrome.google.com/webstore/detail/create-link/gcmghdmnkfdbncmnmlkkglmnnhagajbm

Anyway, great job with this addon.  Small request.

Can you build in the functionality to set a keyboard shortcut to copy (Command + Shift + C  is what I use in Chrome)?  And let me define which option that uses to copy?

Thanks!

**Comment by k08045kk** [comment]
v1.3.0をリリースしました。

ショートカット機能を使用できます。

これがあなたの要望を満たしていることを願っています。
