### ISSUE TITLE
title

### ISSUE THREAD

**Issue by RadrigoFomins** [k08045kk/CopyTabTitleUrl#38]
Возможно сделать, чтобы {title} копировал из meta property="og:title"?

<title></title> часто добавляют в конец название сайта

**Comment by k08045kk** [comment]
現在のCopyTabTitleUrlは、「og:title」（もしくは、「og:site_name」）をコピーすることはできません。
現在のCopyTabTitleUrlは、ウェブページのHTMLにアクセスする権限がありません。権限を意図的に取得していません。そのため、「og:title」にアクセスできません。
参照：https://github.com/k08045kk/CopyTabTitleUrl/issues/17

「 - 」「 | 」「 / 」などの区切り文字以降の文字列を取得する関数を提供することはできるかもしれません。ただし、この方法がすべてのページでサイト名を取得できるとは限りません。
例：
  ${title.tail()}
  ${title}.tail()

**Comment by k08045kk** [comment]
本件の主題は解決済みだと考えるため、問題を閉じます。
区切り文字以降の文字列を取得する関数について議論が必要な場合、別の問題として起票しなおしてください。関数の提供は、現時点で未定です。（関数提供については、#14 なども関連しています）
