### ISSUE TITLE
Custom Format - remove string from tab title AND copy part of string from URL

### ISSUE THREAD

**Issue by charlx** [k08045kk/CopyTabTitleUrl#47]
![image](https://user-images.githubusercontent.com/46587193/150244304-efd1612d-3ba0-48bd-b956-1433fce24c6c.png)

.

Hi toshi, can you help me with this custom format, please  :)

.

- **Tab Title  :**  Countdowns by ScorpVFX on Envato Elements

- **URL  :**  https://elements.envato.com/countdowns-DZ783Q9

.

- ### What I  Want to Do  :

.

**1.  Copy Tab title  :**  Countdowns by ScorpVFX on Envato Elements

**2.  Remove "_on Envato Elements_"  from tab title** =  Countdowns by ScorpVFX

.

**3. Copy '_last portion_' of URL after last hyphen  :**  DZ783Q9

**4. Add result from step 2 + step 3** 

.

**Final Result  :**  Countdowns by ScorpVFX DZ783Q9

**Comment by k08045kk** [comment]
In the current version (v2.2.0), there is no function to copy a part of the title string, and URLs cannot be freely processed either.

For complex processing, we suggest that you use a text editor or program to process the title and URL after copying them.

That's all.

**Comment by charlx** [comment]
> In the current version (v2.2.0), there is no function to copy a part of the title string, and URLs cannot be freely processed either.

Okay toshi, thanks a lot for this nice time saving Extension🥇
