### ISSUE TITLE
Android Firefox 対応（v107+）

### ISSUE THREAD

**Issue by k08045kk** [k08045kk/CopyTabTitleUrl#54]
参考
https://gigazine.net/news/20221023-firefox-beta-android-add-on/

Android Firefox Bate 107+ から再度 Android Firefox で拡張機能が利用可能となった。

CopyTabTitleUrl v2.3.2 がインストール可能
ただし、設定画面が正常に動作していない。だが、タイトル・URLのコピーは、動作しているため、最低限は動作する。

デバッグ環境を準備できれば対応したい。

**Comment by touwys** [comment]
@k08045kk toshi

This surely is one of the most useful add-ons for Firefox, which is also well-supported by the author, thank you. Thus, if you can support CopyTabTitleUrl Firefox on Android devices soon, it would give rise to a most welcome addition.

_Note: By sheer good luck, I have got CopyTabTitleUrl installed for Firefox v115 on an Android tablet where it's made use of, daily. Although some of its configuration settings there are either absent or rendered invisible, the basics are still functional._

**Comment by k08045kk** [comment]
2023年12月14日 Firefox 121 で Android Firefox のアドオンが正式にサポートされました。

Firefox for Android 121.0, See All New Features, Updates and Fixes
https://www.mozilla.org/en-US/firefox/android/121.0/releasenotes/
ついにAndroid版Firefoxで拡張機能が使用可能に、すでに450種以上のアドオンが利用可能 - GIGAZINE
https://gigazine.net/news/20231215-android-firefox-addon-debut/

**Comment by k08045kk** [comment]
覚書
Kiwi Browser の動作確認も合わせて実施すること

**Comment by touwys** [comment]
Unless I am mistaken, CopyTabTitleUrl is not yet released for the stable version of Firefox (Android). Could you please make it available for that platform?

**Comment by k08045kk** [comment]
There are no misunderstandings. When the issue is closed, it will be released on Firefox (Android). (Or give up on development.) However, this is a problem that has already been going on for a year. Please wait without any expectations.

**Comment by k08045kk** [comment]
v3.2.0 でリリース
Android 対応は完了しました。個別の不具合は、別の Issue を立ててください。

残件等は、次ページを参照してください。
https://github.com/k08045kk/CopyTabTitleUrl/wiki/Mobile
+ Can't get the intended tab with target window / all
