### ISSUE TITLE
How to Format?

### ISSUE THREAD

**Issue by touwys** [k08045kk/CopyTabTitleUrl#55]
Thank you for this excellent add-on.

I want to copy and the paste the webpage title — into which the url is embedded — into **Telegram** messenger. What is the correct and best CopyTabUrl format string to use to achieve this?

Thank you.

**Comment by k08045kk** [comment]
I should start by saying that I am not familiar with Telegram messenger.

As far as I have researched, the Telegram Bot API seems to support Markdown and HTML Link. However, there is no format available unless you use the Telegram Bot API. There is only a link creation function by GUI operation and shortcut.

Example:
+ Markdown: `[${title}](${url})`
+ HTML Link: `<a href="${url}">${title}</a>`

that's all.

**Comment by touwys** [comment]
Thank you.

**Comment by k08045kk** [comment]
I believe the issue is resolved, so I'm closing the issue.
If the issue persists, please add a comment or create a new issue.
