### ISSUE TITLE
[Feature request] "Copy all to the left/right"

### ISSUE THREAD

**Issue by ohhai** [k08045kk/CopyTabTitleUrl#57]
It would be great to have two more items in the context menu:
"Copy all tabs to the left" and "Copy all tabs to the right" (from the currently selected tab).

Why: it would be very useful in any workflow when I open a lot of tabs and want to process them later.
Currently, I just leave them as open tabs. It creates a mess in the tab list and my browser gets slower because of them (hundreds+ tabs sometimes). Such copying will allow me to keep those tabs out of my browser, so it will be clean and fast.

I can do something similar by opening "removable" tabs in a separate window and then copying URLs and titles for that entire window - but it requires prediction of what tabs will be moved. It's not always possible.
Same lack of prediction relates to a possible way of immediate copying of url+title instead of opening it.

Thank you for the great extension!

Firefox 119
CopyTabTitleUrl 2.3.2

**Comment by k08045kk** [comment]
Hello

Is it possible to replace it with a function that copies "multiple selection tabs"?

How to use it is as follows.
1. Please enable "Enable multiple selection tabs" in the options. (Enabled by default)
2. Please select multiple tabs in your browser. (You can use the Shift and Ctrl keys to select multiple tabs using standard browser functionality.)
3. Execute the copy function of this extension with multiple tabs selected. (Please use the copy function for regular tabs, not "All" or "Window")
4. That way, you can copy only the information from the selected tab.

that's all.

**Comment by ohhai** [comment]
After 20 years on Internet, I just learned how multiple tabs can be selected :)
Thank you!
Seems like shift-selection might be the case because it doesn't require an action for every tab and keeps rest of the flow as I need.
I close this ticket and will update it if any new details arrive.
