### ISSUE TITLE
Firefox - copy from context menu does not work

### ISSUE THREAD

**Issue by smaragdus** [k08045kk/CopyTabTitleUrl#6]
Hello,

In added **CopyTabTitleUrl** extension to both **Chromium** (version **1.5.2**) and **Firefox** (version **1.5.3**) and I use the same settings- screens:

**Chromium:**
![CopyTabTitleUrl 1 5 2 - Chromium - 2019-05-25 - 002](https://user-images.githubusercontent.com/9025757/58368820-e4f9a300-7efa-11e9-8649-50eac7c16718.png)

**Firefox:**
![CopyTabTitleUrl 1 5 3 - Firefox - 2019-05-25 - 002](https://user-images.githubusercontent.com/9025757/58368824-f3e05580-7efa-11e9-947c-172c02eada46.png)

and 'copy from context menu' works in **Chromium** while it does not work in **Firefox**. In **Firefox** I tried  to copy both from tab context menu and from page context menu and both copy actions failed. What settings I am supposed to use in **Firefox** to be able to copy from context menu?

Regards

**Comment by k08045kk** [comment]
Hello.

質問を受け付けました。ですが、問題を解決することはできません。
基本的にFirefoxに対する特別な設定は不要だと考えています。
また、私の環境ではFirefoxでコンテキストメニューからコピーすることができます。
そのため、問題が発生するパターンを特定したいと私は考えています。

次の認識であっていますか？
+ Chromiumでは動作する。問題はない。対応する必要はない。
+ Firefoxでは動作しない。問題がある。対応する必要がある。
+ 拡張機能のバージョンは、v1.5.3（現状最新）である。
+ コンテキストメニューからコピーすることができない。

次の質問に回答頂けませんか？
+ Firefoxのブラウザバージョンはなんですか？
+ 拡張機能の設定で「Other」の設定内容はなんですか？（可能であれば、拡張機能の設定すべてのスクリーンショットが見たい）
+ ブラウザアクションやショートカットからコピーすることはできますか？
+ どのコンテキストメニューからコピーしましたか？（Page or Selection or BrowserAction or Tab）
+ コンテキストメニューのコピーとは、具体的にどのコピーで失敗しましたか？（「Copy tab title and URL」or「Copy tab title」or その他）
+ 具体的にどんなページにコピーを実行しましたか？（次のページで失敗しますか？：https://github.com/k08045kk/CopyTabTitleUrl）
+ OSやFirefoxを再起動しても問題は解決しませんか？
+ 拡張機能を再インストールしても問題は解決しませんか？

**Comment by smaragdus** [comment]
Hello and thank you very much for taking your time to respond to my problem.

I use a custom build of **Firefox** called [Iceweasel](https://sourceforge.net/projects/libportable/), the version I use is [67.0](https://sourceforge.net/projects/libportable/files/Iceweasel/Stable/67.x/):

![snipaste-2019-06-01_054518](https://user-images.githubusercontent.com/9025757/58742891-95523480-8430-11e9-902c-edde2db9cf16.png)

I discovered what is causing the problem. I had made many changes in the browser settings. So I started another instance of the browser with the default settings and **Copy** worked fine in **Iceweasel** just like in **Chromium**. I found what setting in **about:config** prevents **CopyTabTitleUrl** from working from context menu- if I change:

`browser.tabs.remote.autostart`

from **true** to **false**

**Copy** does not work from context menu and from tab.

If I revert the setting

`browser.tabs.remote.autostart`

from **false** to **true**

**Copy** works from context menu and from tab.

In short- if `browser.tabs.remote.autostart` is changed from **true** to **false**, then **Copy** does not work from context menu. Please confirm.

I am glad that I found out what caused my problems with CopyTabTitleUrl- if multiprocessor support is disabled **CopyTabTitleUrl** does not work from context menu.

**Comment by k08045kk** [comment]
調査ありがとうございます。

browser.tabs.remote.autostart
false

上記の設定とした場合、Firefox v67.0で問題現象が発生することを確認しました。
コンテキストメニューとショートカットからのコピーが失敗します。
ブラウザアクションは、一部動作するようです。

また、Firefox Developer Edition v68.0b6で問題現象が発生しないことも確認しました。
正常にコンテキストメニューからコピーできました。

結論
修正方法が不明であり。about:configを意図的に変更しないと発生しない問題であり。最新環境で正常動作するため、**修正を見送ります。**
