### ISSUE TITLE
[Feature Request] Copy Decoded Link When Right Click A Link In Web Page

### ISSUE THREAD

**Issue by Jiang10086** [k08045kk/CopyTabTitleUrl#73]
日本語版は下部にGoogle翻訳が付いています。

Hi, thanks for developing this wonderful extension, which enabled me share human readable link.
But I am wondering if I can directly right click a link in a web page through that extension.
For example, an article have many links, and I want to copy an Unicode version url in this article. By now, I can only open it in a new tab and then copy the decoded url.

The following is an Japanese translation by Google translate of the above text.

こんにちは。人間が読めるリンクを共有できる素晴らしい拡張機能を開発していただきありがとうございます。
しかし、その拡張機能を使用して Web ページ内のリンクを直接右クリックできるかどうか疑問に思っています。
たとえば、記事には多くのリンクがあり、この記事内の Unicode バージョンの URL をコピーしたいとします。 今のところ、新しいタブで開いて、デコードされた URL をコピーすることしかできません。

**Comment by k08045kk** [comment]
Hi. To use the destination URL in the link context menu, the following format field is available:

+ ${linkUrl}
+ ${linkSrcUrl}
+ ${srcLinkUrl}
+ ${infoLinkUrl}

You may also need:

+ ${text}
+ ${selectionText}
+ ${linkText}
+ ${linkSelectionTitle}
+ ${selectionLinkTitle}
+ ${infoLinkText}
+ ${infoSelectionText}


There is also an idea for the next format item, but it has not yet been implemented.

${pageAhrefs}, ${pageSelectionAhrefs}, ${pagePointerAhref}


If you are thinking of formatting and copying multiple links in an article by link, this is not the purpose of this extension. You can copy individual pages, but you cannot copy individual links on pages. It is best to open all the necessary links in the article in one window and copy the window tabs at once.


See the next page for details on the format item.
https://github.com/k08045kk/CopyTabTitleUrl/wiki/Format


That's all.

**Comment by Jiang10086** [comment]
> Hi. To use the destination URL in the link context menu, the following format field is available:
> 
>     * ${linkUrl}
> 
>     * ${linkSrcUrl}
> 
>     * ${srcLinkUrl}
> 
>     * ${infoLinkUrl}
> 
> 
> You may also need:
> 
>     * ${text}
> 
>     * ${selectionText}
> 
>     * ${linkText}
> 
>     * ${linkSelectionTitle}
> 
>     * ${selectionLinkTitle}
> 
>     * ${infoLinkText}
> 
>     * ${infoSelectionText}
> 
> 
> There is also an idea for the next format item, but it has not yet been implemented.
> 
> ${pageAhrefs}, ${pageSelectionAhrefs}, ${pagePointerAhref}
> 
> If you are thinking of formatting and copying multiple links in an article by link, this is not the purpose of this extension. You can copy individual pages, but you cannot copy individual links on pages. It is best to open all the necessary links in the article in one window and copy the window tabs at once.
> 
> See the next page for details on the format item. [https://GitHub.com/k08045kk/CopyTabTitleUrl/wiki/Format](https://github.com/k08045kk/CopyTabTitleUrl/wiki/Format)
> 
> That's all.

No, I am not going to copy multiply links, but only the one on which I right click upon. Regularly doing is:
1. Right click an link in a page
2. Click "Copy The Link"

But this will get a URL encoded link, so I am wondering if this extension can provide an context menu, when I click it, I got an Unicode version of this link.

**Comment by Jiang10086** [comment]
I don't know if I make it clear, if not, feel free to let me know.

**Comment by k08045kk** [comment]
This explains how to use the link context menu.

1. Enable [Use Extended Mode].
2. Enable [link] in the context menu.
3. Enable [format2] in the context menu.
4. Set the format to format2.
   Example: format2 = ${linkUrl}
5. Right-click the link on the page and select format2.
   You can copy formatting that includes the destination URL of the link instead of the page URL.


If Unicode version is Percent Encoding and Punycode, please enable or disable the following settings.

[Decode the URL] 
Example: Enable:  https://translate.google.co.jp/?text=日本語
Example: Disable: https://translate.google.co.jp/?text=%E6%97%A5%E6%9C%AC%E8%AA%9E 

[Decode the Punycode] 
Example: Enable:  https://日本語.jp/
Example: Disable: https://xn--wgv71a119e.jp/ 


That's all.

**Comment by Jiang10086** [comment]
> This explains how to use the link context menu.
> 
>     1. Enable [Use Extended Mode].
> 
>     2. Enable [link] in the context menu.
> 
>     3. Enable [format2] in the context menu.
> 
>     4. Set the format to format2.
>        Example: format2 = ${linkUrl}
> 
>     5. Right-click the link on the page and select format2.
>        You can copy formatting that includes the destination URL of the link instead of the page URL.
> 
> 
> If Unicode version is Percent Encoding and Punycode, please enable or disable the following settings.
> 
> [Decode the URL] Example: Enable: [https://translate.Google.co.jp/?text=日本語](https://translate.google.co.jp/?text=%E6%97%A5%E6%9C%AC%E8%AA%9E) Example: Disable: [https://translate.Google.co.jp/?text=%E6%97%A5%E6%9C%AC%E8%AA%9E](https://translate.google.co.jp/?text=%E6%97%A5%E6%9C%AC%E8%AA%9E)
> 
> [Decode the Punycode] Example: Enable: [https://日本語.jp/](https://%E6%97%A5%E6%9C%AC%E8%AA%9E.jp/) Example: Disable: https://xn--wgv71a119e.jp/
> 
> That's all.

That's wonderful, I managed to did this, thanks for your detailed instruction.
