### ISSUE TITLE
【use】copy All tabs

### ISSUE THREAD

**Issue by ouyoungs** [k08045kk/CopyTabTitleUrl#74]
the old version is easy to copy All tabs,  but now , is hard to do this.

**Comment by k08045kk** [comment]
Please give me a specific example of "being able to easily copy all tabs."
With full use of the settings, the system should have been created to achieve the same usability as before.

For configuration details, please refer to the following document:
https://github.com/k08045kk/CopyTabTitleUrl/wiki/Options

Example:
I used to use [title and URL (all tabs)] in the context menu, but I am having trouble with it now that it is gone.

Example answer:
Enable [Use Extended Mode].
Enable the context menu for [format].
Change the title of [format] to [title and URL (all tabs)].
Change the target of [format] to [all].
Change Format of [format] to [${title}${enter}${url}].

**Comment by ouyoungs** [comment]
that solved my problem, thanks.  it's hard to find this menus.

**Comment by ouyoungs** [comment]
that solved my problem, thanks.  it's hard to find this menus.
