### ISSUE TITLE
Feature Request : Copy Tab and/or Title of Selected URLs

### ISSUE THREAD

**Issue by Bamajon1974** [k08045kk/CopyTabTitleUrl#9]
Feature Request : Copy Tab and/or Title of Selected URLs

Can you implement the ability to select a group of links and either open selected links or copy selected links? Additionally, when one selects links, can you add a submenu to copy title and/or links and copy links as a list or one continuous line? 

Thanks in advance!

**Comment by k08045kk** [comment]
新しいアイディアをありがとう。
私は、あなたの要望を次のように理解しました。そして、その回答を記載します。

1. テキスト選択コンテキストメニューから選択した文字列中に含まれる複数または単数の「リンクを開く」機能
  + 拡張機能の本質から外れるため、実装できません
  + リンクをコピーすることはできます。ですが、開くことはできません
2. テキスト選択コンテキストメニューから選択した文字列中に含まれる複数または単数のリンク（`<a>`）から「タイトルとURLをコピーする」機能
  + テキスト選択コンテキストメニューからURLを取得できないようです
    + 現状の実装を諦めます
  + HTML形式で選択文字列を取得できない
3. リンク選択コンテキストメニューから選択したリンクを「タイトルとURLでコピーする」機能
	+ リンク選択コンテキストメニューからタイトルを取得できないようです
    + 現状の実装を諦めます
  + linkUrlしか取得できない

※2.に関して現行の「選択文字列をタイトルの代用文字列として使用する」機能と干渉する可能性があります
※2.3.について、contentScripts等を利用して実現できる機能だと思われます
　ただし、CopyTabTitleUrlは名前の示す通り、Tabに対しての拡張機能です。Pageに対してではありません。そのため、私はcontentScripts権限をこの拡張機能に与えたくありません

**Comment by Bamajon1974** [comment]
I'm not sure I quite understand your reply as the Google Translate doesn't
work very well. Do you speak English or recommend a better translator?

Thanks, Jon

**Comment by k08045kk** [comment]
私は、今回あなたが何を言いたいのかわからない。英語は話せないです。翻訳者は必要としていません。Google翻訳で理解できない内容わかりません。簡単で、わかりやすく、具体的な内容の説明があれば、私は理解できます。
